services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6500:44278
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: